### ISSUE TITLE
bug: unable to write when cli build on inquirer

### ISSUE THREAD

**Issue by unix** [node-modules/coffee#76]
## Environment
- node.js: v9.10.0
- npm: v6.5.0
- inquirer: v6.2.1

## Details
when I use`.write` in inquirer cli, nothing happened.

example (debug information always stays before `.writeKey 'ENTER'`):
```coffeescript
instance
      .writeKey 'DOWN'
      .writeKey 'ENTER'
      .write 'xxxxxxx'
      .write 'xxxxxxx'
      .writeKey 'ENTER'
      .debug()
      .write 'abcabcabc'
      .writeKey 'ENTER'
      .expect 'code', 1
      .end(() ->)
```

## Screenshots
actually, when I enter any key here, command line should be an output. but there was nothing.

![1 1](https://user-images.githubusercontent.com/11304944/51085494-1e641a00-1775-11e9-87fb-92f1e92d289d.png)

## Links

you can fork my repo for debugging: [fine.sh-cli](https://github.com/WittBulter/fine.sh-cli/blob/test/test/settings/initiator.coffee)

**Comment by popomore** [comment]
The testcase should wait the command. You can pass the callback to the end method, otherwise end method will return a promise, you can await it.

**Comment by atian25** [comment]
@unix use `.waitForPrompt()`

and you need to extends inquirer, see https://github.com/node-modules/common-bin-plus/blob/master/lib/command.js#L89
